
export const FETCH_POSTS_PROGRESS = 'FETCH_POSTS_PROGRESS'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const CREATE_POST_PROGRESS = 'CREATE_POSTS_PROGRESS'
export const CREATE_POST_SUCCESS = 'CREATE_POSTS_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POSTS_ERROR'
